In [1]:
import jieba

In [5]:
from gensim import models


In [2]:
#import gensim

In [6]:
sentences = models.word2vec.LineSentence("cut_file.txt")

In [7]:
models.word2vec.Word2Vec?

In [8]:
model = models.word2vec.Word2Vec(sentences, size=100, window=5, min_count=5, workers=1)

In [9]:
import sklearn

In [10]:
model.syn0

array([[-0.0424047 , -0.16814834, -0.18714693, ..., -0.16629411,
        -0.17130528, -0.09870252],
       [-0.18571027, -0.07561489, -0.04773569, ...,  0.0962159 ,
         0.06955807,  0.11627045],
       [ 0.09511523, -0.01922547,  0.15365002, ...,  0.17513895,
         0.00626201,  0.14468315],
       ..., 
       [ 0.01865397, -0.038095  ,  0.02018585, ...,  0.01117369,
        -0.02977234, -0.00032699],
       [-0.06336466, -0.13311622, -0.01966847, ...,  0.31222209,
         0.08648232,  0.25210238],
       [-0.06504581, -0.05875927,  0.0327829 , ..., -0.11544801,
         0.03072935,  0.21284144]], dtype=float32)

In [7]:
model.syn0.shape

(20059, 100)

In [11]:
len(model.vocab)

20059

In [12]:
model.syn1.shape

(20059, 100)

In [13]:
from sklearn import  cluster


In [14]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram

In [15]:
kmean = cluster.KMeans(n_clusters=10)

In [16]:
result = kmean.fit(model.syn0)

In [18]:
result.labels_

array([6, 1, 8, ..., 8, 1, 8])

In [19]:
print " ".join(np.array(model.index2word)[result.labels_ == 1])

台灣金 礦 河 屏東 台灣醒 第一 含金量 譜 奶茶 將配 麥嘉華 活 大圓環 配 外媒 通訊社 公車 塔利班 。台灣 結算週 機 外快 夜市 林惟真 起跑 張 Facebook 台新金 榮譽 農 1030310 1030317 校院 外幣 政院 楊照 畢業生 平台 偵辦 302 Le 自台灣 台大 外受 實境頭 學士 英國國家 性感女 仇者 金秀賢 世界 Chen Ｂ FaceBook 莊 s 合醜蝶 快換 農委會 24.27 霧 邱國強 勇救 護台灣 太平 ▇ 關於針對 NC 昱 截稿 惊 非商業性 通信 五 experience 實弱 more 總工會 大台 交易日 澳洲 秀沛 徐斯儉 纜車 孫仲達 麗嬰房 3C 1030324 1030320 1030322 319 量化 口至 余艾苔 濺 擴及 絲 卡麥蓉 月薪 空氣 影 洛杉磯 登入須 百分之九十 千 指定 微軟 行腳 逛 白宮 押解 晶電 仇 澳大利 杭州 大字 One 設宴 專家 塑膠 遭警 天價 首周 無雙 組 囉 天公 業從業 亮相 iPad 駐日 天在 周年 明政 張家祝 亮眼 web 广末凉子 Doors 明星 大小 大專 具業 大展 VOA 隆 金門 個 明報 大成 關於服貿 鴨 女藝 駐 12.5 不靠 這篇 儲祥生 Q1 哲和前 大意 QE 古坑 十五 吋 開 本 憑證 郝明 挺外 員 鱟 參訪團 潘基文 重量 天氣 5478 週年慶 iOS 多則 稅後盈餘為 天津 五大 安平 私塾 大樓 WhatsApp 穿著 誤信 史坦 營運長 大步 零時 露 最快 實收 促允退 成人 不黑 投資長 監事 毫 淨 集團 交易中心 讚 榮 澳元 154 天會 社長 抱抱 平盤 五包 艾琳 中华 吳慷仁 冷氣團 0.59 1859 藥品 東 股特區 多家 施及 天空 保一 勇士 趙 尋他 五一 阿土 注 大片 狂飆 保住 款待 80hrs 王乙徹 戰報 悲慘 報道 供應 縣黨部 繆宇綸 大直 外海 永豐金控 宜蘭 查扣 強勁 師認 投資術 明中 MWC 發國際 蔡黃 ！ 傅 平沼 為準 曲線 商業行 路段 e 票房 0.23 德州 夾議場 吳翊寧攝 外傳 指當 講座 外患 清大 link1 國際 onlineopinions 游 最佳 太陽能 副手 怒 煤气 8577 ＝ 身價 重返 蘋果 伊莉莎白 傳

In [20]:
index = result.labels_ == 3

In [21]:
d = pdist(np.array(model.syn0)[index])

In [22]:
m = linkage(d, method='average')


In [23]:
h = hierarchical.hierarchy.fcluster(m, 0.5*d.max(), 'distance')

NameError: name 'hierarchical' is not defined

In [24]:
from collections import Counter

In [25]:
Counter(h)

NameError: name 'h' is not defined

In [89]:
w = np.array(model.index2word)[index]

In [93]:
print ' '.join(w[h == 7])

將服 送院 存查


In [53]:
for w in iter(model.most_similar(u'立法院')):
    print w[0], w[1]

立院 0.603346586227
行政院 0.603059649467
議場 0.571261405945
第四天 0.496139019728
十八日 0.489799916744
第五天 0.480789452791
學運團體 0.474696993828
。反服 0.460709422827
轉攻 0.458278417587
貿抗 0.456872701645


In [54]:
for w in iter(model.most_similar(u'失業率')):
    print w[0], w[1]

漸降 0.750377655029
大增 0.645602226257
恐迅 0.625342786312
LED 0.606179773808
虛 0.590319693089
這波 0.589477539062
資 0.581196784973
租金 0.579375386238
前年 0.574292063713
幅度 0.573513925076


In [55]:
for w in iter(model.most_similar(u'金融股')):
    print w[0], w[1]

壓抑 0.644614458084
疲弱 0.627895772457
拖累 0.627761721611
股表現 0.612426280975
出脫 0.61090773344
短線 0.610537230968
加碼 0.607644796371
漲多 0.603220820427
股 0.598988771439
祭品 0.589098572731


In [106]:
for w in iter(model.most_similar(u'鴻海')):
    print w[0], w[1]

友達 0.78621506691
可成 0.754890680313
中鋼 0.746079683304
晶睿 0.727296173573
台積電 0.725298523903
南茂 0.724448442459
宏達電 0.724434971809
面板 0.724431276321
地價 0.712866425514
IC 0.712585091591


In [109]:
for w in iter(model.most_similar(u'國民黨')):
    print w[0], w[1]

民進 0.533571720123
委員會 0.508938848972
選區 0.489793121815
林鴻池 0.486383676529
黨 0.484783023596
立委 0.477195084095
出席 0.456923723221
國民黨團 0.447054952383
率人到 0.445269107819
新營 0.440411031246


In [17]:
index = result.labels_ == 3
print " ".join(np.array(model.index2word)[index])

礦 河 反 急動員令 集結 明章 校長 抗議民眾 外宣 可疑分子 服務處 毆 外媒 公車 刑警 將邀 夜宿 疊起 院校 以學生 . 統治正 離 暫 張 諷刺 大紀元 零星 校院 政院 救護 院會針 臉書號 市議員 偵辦 院方 台大 瘓 外包 莊 道路 合醜蝶 成員林 院際會議 公職 霧 周五 周二 貼文 疲憊 外圍 ▇ 關於針對 。反對 截稿 掌聲 路口 急診 即刻 六點 多日 身穿 發出 遭占據 離院 路上 徐斯儉 日 。反服貿 禁食 口號 設備 newtalk2014 稱 破門入 周圍 319 318 將號 大埔 32 當上 余艾苔 導演 擴及 樓 幾項 貼 以馬 空氣 NOWnews 原訂 斷 大喊 小雨 守 開花 發動 以靜 行腳 白宮 進議場 領現 大學 澳大利 One 白天 遭警 通宵 林惠君 組 大門口 張其強 阻止 郁芬 大廳 層層 iPad PO 婷婷 近日 演藝圈 清華大學 擴大 天團 靜 沃草 截止 大專 明時 悶熱 上千人 罪 不間 多名 大批 場面 明天 貿佔領 駐 路線 半左右 天來 留學生 實況 駐守 赴 帶著 哲和前 古坑 十二 燃放鞭炮 保 十一 禾 挺外 員 至今 路程 盈瑜 天氣 多則 多分 現身 待命 奔 發表談 蕃薯藤 看板 阿信 安平 大樓 穿著 保護下 領國會 百名 零時 幾分鐘 監事 移動 遊行 為廷 台北 眼 社長 通牒 吳慷仁 蔡麗青 攝 部前 東 前例 物品 拉 多家 指揮 聲援者 更進 並請 保一 隔離 勇士 尋他 便 致電 傳單 80hrs 但場 三訴 深夜 百位 7 為止 張懸 縣黨部 赦免 組黨 大直 坐學生 。行政院 。反服 物件 關於學生 反服貿 強力 發國際 從議場 強制 至少 突然 路段 外 夾議場 清芳 並與 太陽花 第 路旁 譴責 多人 怒 外抗 多位 東路側 九點 傳 周羿 昏迷 呂秀蓮 上流 游錫堃 蔡正元 有學生 助理 http 夜晚 41 名民眾 十名 外有 帶頭 帶領 議事場 Live 兩旁靜 感謝 院區 餘位 丟 連勝文今 消防 陳昌輝 先天 第一次 全台 台上 台中 院際會商 朝日 力行 學系 飛帆 幹部 全因 並不願 援學生 英文 全國 會理 姓 史上 蔡和穎 VS 第一波 使用 衛視 貿抗 直奔 主辦 下班 地上 敘 總會長 蔣偉寧 所幸 第一手 曾盈瑜 齊聚 吳崑 齊聲 第

In [263]:
for w in iter(sentences):
    print ' '.join(w)

經部 昨天 提出 服貿 協議 本會期 過關 的 因應 策略 向 江揆 報告 ， 同時針 對 服貿 協議 開放 市場 的 敏感性 議題 ， 向 各部 會首長 說明 ， 讓 首長 了解 服貿 協議 對 相關 產業 的 實質 影響 ， 以利 在 立法院 3 月 10 日 之 後 排入 委員會 審議 ， 各部 會 在 攻防 策略 上須 口徑 一致 。

官員 表示 ， 昨天 會議 是 就 外界 關切 的 特定 議題 、 範圍 、 受影響 產業 等 各個 面向 ， 一一 提出 沙盤 推演 ， 針對 在 攻防 策略 上 的 問題 進行 地毯式 搜索 。

官員 表示 ， 簽服 貿協議 對 台灣 不會 有 什麼 衝擊 ， 因 投資 與 貨品 貿易 開放 不同 ， 陸資來 台 投資須 經評 估 ， 若台灣 市場 飽 和 且 無 利基 ， 陸資 不會來 台 投資 ， 以 美容 美 髮 業為例 ， 陸資 只 可能 出資 ， 不 可能 引進 大陸 人士 和 台灣 洗頭妹 助理 搶飯 碗 。

出版 業者 擔心 的 問題 也 不 存在 ， 官員 說 ， 陸方 要求 我 開放 出版 市場 ， 但 我方 提 相互 對 等 開放訴 求 ， 陸方 就 不敢 要求 ， 因大陸 管制 出版 業比 台灣 更 嚴格 ， 開放 目的 在 爭取 陸方 對 大陸 印刷 市場 的 開放 ， 是 提供 我 印刷 業者 進軍大陸 市場 的 空間 。兩岸 金融 監理 首長 會議 應會 延到 下半年 舉行 。 金管會 主委 曾銘宗 昨 （ 13 ） 日 表示 ， 金證 二會 、 金銀四會 及 金保二會 ， 應該 都 會 在 下半年 才能 舉行 ， 主要 是 必須 等 服貿 協議 過關 ， 才能 與 對岸洽 談下 一階段 的 開放 。

金管會 原本 依據 規劃 ， 是 要 在 今年 元月 舉行 第二次 的 金管會 與 大陸證 監會 監理 平台 的 首長 級 會議 ， 4 月則 是 金管會 與 大陸 銀監會 的 第四次 首長 會議 ， 7 月則 是 金管會 與 大陸 保監會 第二次 首長 會議 ， 表 定都 是 要 在 北京 舉行 。

但 去年 元月 首次 金證會 洽談 的 相關 開放 ， 如 提高 大陸 QDII 來 台額度 ， 從 5 億 美元 提高 到 10 億 美元 ， 台灣 券商 可到 大陸設 逾 49 ％ 的

In [18]:
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram

In [19]:
d = pdist(np.array(model.index2word)[index])

In [ ]:
m = linkage(d, method='average')


In [28]:
from sklearn.cluster import hierarchical

In [275]:
h = hierarchical.hierarchy.fcluster(m, )

In [271]:
h

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1,

In [276]:
from collections import Counter

In [278]:
Counter(h)

Counter({29: 13, 5: 9, 41: 9, 89: 9, 10: 8, 54: 8, 62: 7, 130: 7, 61: 6, 66: 6, 84: 6, 111: 6, 16: 5, 20: 5, 91: 5, 93: 5, 98: 5, 100: 5, 118: 5, 120: 5, 12: 4, 19: 4, 50: 4, 53: 4, 63: 4, 65: 4, 69: 4, 72: 4, 73: 4, 74: 4, 90: 4, 102: 4, 104: 4, 129: 4, 1: 3, 4: 3, 7: 3, 8: 3, 13: 3, 14: 3, 15: 3, 22: 3, 23: 3, 28: 3, 35: 3, 36: 3, 37: 3, 40: 3, 47: 3, 48: 3, 59: 3, 60: 3, 67: 3, 68: 3, 71: 3, 78: 3, 79: 3, 80: 3, 82: 3, 95: 3, 96: 3, 101: 3, 107: 3, 108: 3, 127: 3, 128: 3, 2: 2, 3: 2, 9: 2, 11: 2, 17: 2, 18: 2, 21: 2, 24: 2, 25: 2, 26: 2, 27: 2, 30: 2, 31: 2, 32: 2, 33: 2, 39: 2, 44: 2, 45: 2, 46: 2, 49: 2, 51: 2, 52: 2, 55: 2, 56: 2, 57: 2, 58: 2, 64: 2, 70: 2, 76: 2, 77: 2, 81: 2, 85: 2, 86: 2, 87: 2, 92: 2, 94: 2, 97: 2, 103: 2, 109: 2, 110: 2, 112: 2, 113: 2, 114: 2, 115: 2, 117: 2, 119: 2, 121: 2, 122: 2, 123: 2, 124: 2, 125: 2, 126: 2, 6: 1, 34: 1, 38: 1, 42: 1, 43: 1, 75: 1, 83: 1, 88: 1, 99: 1, 105: 1, 106: 1, 116: 1, 131: 1})

In [279]:
print ' '.join(np.array(model.index2word)[h == 29])

反 年底 時間 歷史 互設 以及 16 開議 逐條 本 。「 領域 周五


In [110]:
print ' '.join(np.array(model.index2word)[h == 26])

邦 水 陸 台 奢侈 高 社會 量


In [94]:
import simplejson as json
with open('/Users/apple/Downloads/dump.out') as f:
    docs = f.readlines()


In [95]:
docs2 = [json.loads(d) for d in docs]


In [96]:
print docs2[0]['title']


何壽川：永豐金不排斥併購


In [97]:
import pandas as pd 
test_text_df = pd.DataFrame(docs2)


In [98]:
test_text_df[:10]


content            created_at  \
0  永豐金(2890)晉升百億俱樂部，去年(2013)稅後淨利來到103億元，年增率超過1成，董...  2014-02-13 10:57:33    
1  永豐金控（2890）子公司永豐銀行2013年4月引資大陸中國工商銀行參股20%，雙方簽訂備忘...  2014-02-13 11:00:18    
2  經部昨天提出服貿協議本會期過關的因應策略向江揆報告，同時針對服貿協議開放市場的敏感性議題，向...  2014-02-13 13:06:32    
3  兩岸金融監理首長會議應會延到下半年舉行。金管會主委曾銘宗昨（13）日表示，金證二會、金銀四會...  2014-02-14 08:35:30    
4  統一企業董事長羅智先 (左圖，中央社)昨在春酒上，為台灣流年下註解。他表示，今年是甲午年，和...  2014-02-15 04:33:03    
5  立法院第八屆第五會期本周五開議，國民黨團希望能在上半年通過兩岸服貿協議、自由經濟示範區特別條...  2014-02-16 04:16:48    
6  二○一四年冬季奧運於二月七日在俄國索契（Sochi）隆重登場，賽前賽後話題不斷，選手精彩表現...  2014-02-16 04:17:17    
7  「王張會」互稱官銜，民進黨中央曾公開肯定是進步，不過，因應立院本會期周五開議，一場兩岸大戰又...  2014-02-16 04:17:35    
8  「王張會」互稱官銜，民進黨中央曾公開肯定，惟因應立院本會期開議，一場兩岸大戰將開打，民進黨團...  2014-02-17 04:18:51    
9  馬總統並再度強調，與大陸簽署服務貿易協議的示範作用，是各國觀察台灣經濟自由度以及開放度的重要...  2014-02-17 13:05:09    

                                                link  score     source  \
0    http://www.ettoday.net/news/20140212/324561.htm      1  東森EtToday   
1  http://udn.com/NEWS/BREAKINGNEWS/BREAKINGNEWS6...      2      聯合新聞網   
2  http://www.chinatimes.com/newspapers/201402130...      1       工商時報   
3  http://www.chinatimes.com/newspapers/201402140...      0       工商時報   
4  http://www.chinatimes.com/newspapers/201402150...      1       中國時報   
5  http://udn.com/NEWS/NATIONAL/NAT1/8488616.shtm...      0      聯合新聞網   
6  http://udn.com/NEWS/OPINION/OPI4/8488580.shtml...      0      聯合新聞網   
7  http://www.chinatimes.com/newspapers/201402160...     28       中國時報   
8  http://www.chinatimes.com/newspapers/201402170...     15       中國時報   
9  http://udn.com/NEWS/BREAKINGNEWS/BREAKINGNEWS6...      2      聯合新聞網   

                title  
0        何壽川：永豐金不排斥併購  
1      永豐銀引資大陸工行 可望續約  
2            江揆下部會動員令  
3  服貿需先過關 兩岸金融會議下半年舉行  
4           羅董解盤：今年向上  
5      立院周五開議 綠預言烽火連天  
6       陳冲／在冬運後台看服貿協議  
7   綠營硬堵服貿協議 立院將演兩岸大戰  
8  熱門話題－立院服貿大戰 受苦的是人民  
9  馬總統：服貿具重要示範作用籲加快進程  

[10 rows x 6 columns]

In [99]:
test_text_df['content'][:10]

0    永豐金(2890)晉升百億俱樂部，去年(2013)稅後淨利來到103億元，年增率超過1成，董...
1    永豐金控（2890）子公司永豐銀行2013年4月引資大陸中國工商銀行參股20%，雙方簽訂備忘...
2    經部昨天提出服貿協議本會期過關的因應策略向江揆報告，同時針對服貿協議開放市場的敏感性議題，向...
3    兩岸金融監理首長會議應會延到下半年舉行。金管會主委曾銘宗昨（13）日表示，金證二會、金銀四會...
4    統一企業董事長羅智先 (左圖，中央社)昨在春酒上，為台灣流年下註解。他表示，今年是甲午年，和...
5    立法院第八屆第五會期本周五開議，國民黨團希望能在上半年通過兩岸服貿協議、自由經濟示範區特別條...
6    二○一四年冬季奧運於二月七日在俄國索契（Sochi）隆重登場，賽前賽後話題不斷，選手精彩表現...
7    「王張會」互稱官銜，民進黨中央曾公開肯定是進步，不過，因應立院本會期周五開議，一場兩岸大戰又...
8    「王張會」互稱官銜，民進黨中央曾公開肯定，惟因應立院本會期開議，一場兩岸大戰將開打，民進黨團...
9    馬總統並再度強調，與大陸簽署服務貿易協議的示範作用，是各國觀察台灣經濟自由度以及開放度的重要...
Name: content, dtype: object

In [101]:
import jieba

In [102]:
y = [jieba.cut(sentene, cut_all=True) for sentene in test_text_df['content']]

In [103]:
f2 = open('cut_file_2.txt', 'w')

In [104]:
for w in y:
    w2 = ' '.join(w)
    f2.writelines(w2.encode('utf-8'))

Building Trie..., from /Users/apple/anaconda/lib/python2.7/site-packages/jieba-0.32-py2.7.egg/jieba/dict.txt
loading model from cache /var/folders/zb/v5l_14vn5bd4ymx_rmc3qwww0000gn/T/jieba.cache
loading model cost 1.84629201889 seconds.
Trie has been built succesfully.


In [105]:
f2.close()

In [229]:
y1 = y[0]

In [233]:
x = ' '.join(y1)

In [171]:
f2.writelines()

TypeError: writelines() argument must be a sequence of strings

In [138]:
doc = map(jieba.cut, docs2)

In [140]:
print ' '.join(doc[0])

AttributeError: 'dict' object has no attribute 'decode'